### ISSUE TITLE
Hello, your project is great, can you upload the code to generate “traced_bert.pt”, I am a senior student, doing my own graduation project

### ISSUE THREAD

**Issue by duan348733684** [ericperfect/libtorch_tokenizer#1]
Hello, your project is great, can you upload the code to generate “traced_bert.pt”, I am a senior student, doing my own graduation project.  thx

**Comment by ericperfect** [comment]
You can refer to the following：
https://pytorch.apachecn.org/docs/1.4/30.html
https://zhuanlan.zhihu.com/p/146453159?utm_source=wechat_timeline
